created: 2026-04-14T10:25:24.764Z
updated: 2026-04-14T10:25:24.765Z
update_count: 1
last_field: description
kind: nested-class
title: nlp-processor
children: []
parentPath:
  - core-layer
  - ai-subsystem
