created: 2026-04-14T10:25:52.880Z
updated: 2026-04-14T10:25:52.880Z
update_count: 1
last_field: description
kind: nested-class
title: renderer
children: []
parentPath:
  - generator-layer
  - eb-internals
