created: 2026-04-14T10:25:13.715Z
updated: 2026-04-14T10:25:13.715Z
update_count: 1
last_field: description
kind: nested-class
title: definition-model
children: []
parentPath:
  - core-layer
  - model
