/**
 * Template Syntax Verification Test
 * This template exercises all XPath patterns and directives from Can.xdm
 * Generated by: BSW Configurator Template Engine
 */

/*****************************************************************************
 * SECTION 1: Variable Declarations (VAR directive)
 * Tests: [!VAR ... = "..."!]
 *****************************************************************************/
[!VAR "MaxModules" = "2"!]
[!VAR "MaxNodes" = "4"!]
[!VAR "TestString" = "'/Can/Can/CanController'"!]
[!VAR "TestList" = "'A,B,C,D'"!]

/* Test Results - Variable Values */
#define TEST_MAX_MODULES    ([!"$MaxModules"!]U)
#define TEST_MAX_NODES      ([!"$MaxNodes"!]U)

/*****************************************************************************
 * SECTION 2: FOR Loop with Expression Evaluation
 * Tests: [!FOR "var" = "start" TO "end"!] with count() expression
 *****************************************************************************/
/* FOR loop with literal values */
[!FOR "i" = "1" TO "4"!]
#define TEST_ITEM_[!"$i"!]    ([!"$i"!]U)
[!ENDFOR!]

/* FOR loop with count() expression */
[!FOR "v" = "1" TO "count(text:split($TestList, ','))"!]
[!VAR "ItemId" = "text:split($TestList, ',')[num:i($v)]"!]
#define TEST_SPLIT_[!"$v"!]   ("[!"$ItemId"!]")  /* Index [!"$v"!] */
[!ENDFOR!]

/*****************************************************************************
 * SECTION 3: String Functions
 * Tests: substring-after, substring-before, text:split, text:tolower
 *****************************************************************************/
[!VAR "PathValue" = "'/Can/Can/CanController_0'"!]
#define PATH_FULL       "[!"$PathValue"!]"
#define PATH_AFTER      "[!substring-after($PathValue, 'Can/')!]"
#define PATH_BEFORE     "[!substring-before($PathValue, '/CanController')!]"
#define PATH_LOWER      "[!text:tolower($PathValue)!]"

/*****************************************************************************
 * SECTION 4: Numeric Functions
 * Tests: num:i, num:hextoint, num:inttohex
 *****************************************************************************/
[!VAR "HexValue" = "'0x1A'"!]
[!VAR "IntValue" = "42"!]
#define INT_FROM_STR    ([!num:i("15")!]U)
#define HEX_TO_INT      ([!num:hextoint($HexValue)!]U)
#define INT_TO_HEX      ([!num:inttohex($IntValue)!]U)

/*****************************************************************************
 * SECTION 5: Boolean and Condition Evaluation
 * Tests: IF/ELSE/ENDIF, boolean comparison, AND/OR conditions
 *****************************************************************************/
[!VAR "EnableFeature" = "'true'"!]
[!VAR "DisableFeature" = "'false'"!]
[!VAR "CountValue" = "5"!]

/* Simple boolean check */
#define FEATURE_A_ENABLED   [!IF "$EnableFeature = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
#define FEATURE_B_ENABLED   [!IF "$DisableFeature = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/* Numeric comparison */
#define COUNT_GT_3          [!IF "$CountValue > 3"!](TRUE)[!ELSE!](FALSE)[!ENDIF!]
#define COUNT_LT_10         [!IF "$CountValue < 10"!](TRUE)[!ELSE!](FALSE)[!ENDIF!]
#define COUNT_EQ_5          [!IF "$CountValue = 5"!](TRUE)[!ELSE!](FALSE)[!ENDIF!]

/* AND condition with parentheses */
#define AND_CONDITION_1     [!IF "(num:i($CountValue) > 3) and ($EnableFeature = 'true')"!](TRUE)[!ELSE!](FALSE)[!ENDIF!]

/* OR condition */
#define OR_CONDITION_1      [!IF "($DisableFeature = 'true') or ($CountValue > 3)"!](TRUE)[!ELSE!](FALSE)[!ENDIF!]

/* NOT condition */
#define NOT_CONDITION       [!IF "not($DisableFeature = 'true')"!](TRUE)[!ELSE!](FALSE)[!ENDIF!]

/*****************************************************************************
 * SECTION 6: LOOP with Module Configuration
 * Tests: LOOP, as:modconf, node:name, node:value, node:path, node:exists
 *****************************************************************************/
[!LOOP "as:modconf('Can')/CanConfigSet/*"!]
/* --------------------------------
 * Controller: [!node:name(.)!]
 * Path: [!node:path(.)!]
 * -------------------------------- */
[!IF "node:exists(CanControllerId)"!]
#define [!text:toupper(node:name(.))!]_ID    ([!CanControllerId!]U)
[!ENDIF!]
[!IF "node:exists(CanControllerActivation)"!]
#define [!text:toupper(node:name(.))!]_ACTIVE    [!IF "CanControllerActivation = 'true'"!](TRUE)[!ELSE!](FALSE)[!ENDIF!]
[!ENDIF!]
[!ENDLOOP!]

/*****************************************************************************
 * SECTION 7: node:fallback() Function
 * Tests: node:fallback with default values
 *****************************************************************************/
[!LOOP "as:modconf('Can')/CanConfigSet/*"!]
[!VAR "FallbackId" = "node:fallback(CanControllerId, 999)"!]
#define [!node:name(.)!]_FALLBACK_ID    ([!"$FallbackId"!]U)
[!ENDLOOP!]

/*****************************************************************************
 * SECTION 8: count() Function
 * Tests: count() to get number of items
 *****************************************************************************/
#define TOTAL_CAN_CONTROLLERS    ([!count(as:modconf('Can')/CanConfigSet/*)!]U)

/*****************************************************************************
 * SECTION 9: Complex AND Conditions (From Can.xdm validation rules)
 * Tests: (node:exists(X)) and (Y = 'true') pattern
 *****************************************************************************/
[!LOOP "as:modconf('Can')/CanConfigSet/*"!]
/* Testing complex AND condition for [!node:name(.)!] */
[!IF "(node:exists(CanFDSupport)) and (CanFDSupport = 'true')"!]
#define [!node:name(.)!]_FD_ENABLED    (TRUE)  /* FD is enabled */
[!ELSE!]
#define [!node:name(.)!]_FD_ENABLED    (FALSE) /* FD is disabled */
[!ENDIF!]
[!ENDLOOP!]

/*****************************************************************************
 * SECTION 10: INDENT and Indentation Control
 * Tests: [!INDENT "N"!] directive
 *****************************************************************************/
static const uint8 TestArray[] =
{
[!INDENT "4"!]
[!FOR "i" = "1" TO "3"!]
(uint8)[!"$i"!]U,    /* Element [!"$i"!] */
[!ENDFOR!]
[!ENDINDENT!]
};

/*****************************************************************************
 * SECTION 11: SELECT and Node Context Switch
 * Tests: [!SELECT ...!] directive
 *****************************************************************************/
[!LOOP "as:modconf('Can')/CanConfigSet/*"!]
[!SELECT "."!]
/* SELECT context for [!node:name(.)!] */
[!IF "node:exists(CanControllerId)"!]
#define SELECT_[!node:name(.)!]_ID    ([!CanControllerId!]U)
[!ENDIF!]
[!ENDSELECT!]
[!ENDLOOP!]

/*****************************************************************************
 * SECTION 12: node:order() Sorting
 * Tests: Sorting loop items by a parameter
 *****************************************************************************/
/* Controllers sorted by CanControllerId */
[!LOOP "node:order(as:modconf('Can')/CanConfigSet/*, 'CanControllerId')"!]
/* Sorted: [!node:name(.)!] - ID=[!node:fallback(CanControllerId, 0)!] */
[!ENDLOOP!]

/*****************************************************************************
 * SECTION 13: ELSEIF Chains
 * Tests: [!IF ... !][!ELSEIF ... !][!ELSE!][!ENDIF!]
 *****************************************************************************/
[!VAR "Mode" = "'POLLING'"!]
#define PROCESSING_MODE    [!IF "$Mode = 'INTERRUPT'"!](0U)[!ELSEIF "$Mode = 'POLLING'"!](1U)[!ELSEIF "$Mode = 'MIXED'"!](2U)[!ELSE!](255U)[!ENDIF!]

/*****************************************************************************
 * END OF TEMPLATE
 *****************************************************************************/
