created: 2026-04-14T10:25:02.518Z
updated: 2026-04-14T10:25:02.519Z
update_count: 1
last_field: description
kind: nested-class
title: dependency-graph
children: []
parentPath:
  - ui-layer
  - widgets
